### ISSUE TITLE
Parse error

### ISSUE THREAD

**Issue by mapsteps** [vlthemes/VLThemes-Add-Typekit-fonts-to-Kirki#1]
Hey @vlthemes,

thanks for this awesome piece of code!

I'm getting the following error on a server running php 5.6

Parse error: syntax error, unexpected T_BOOLEAN_AND, expecting ')' in /path/to/website on line 29

which is this line:

`if($this->typekit_enable && !empty($this->_typekit_id && $this->typekit_fonts)){`

**Comment by vlthemes** [comment]
Hi!

Fixed, try it again.

**Comment by mapsteps** [comment]
That was fast,

thanks a ton! :)
