### ISSUE TITLE
Register multiple optgroups with kirki

### ISSUE THREAD

**Issue by mapsteps** [vlthemes/VLThemes-Add-Typekit-fonts-to-Kirki#3]
Hey @vlthemes,

how's it going? :)

Did you ever need to implement more than one additional optgroup to the kirki typography dropdown with the new setup in kirki?. I've put together some ideas over here (https://github.com/aristath/kirki/issues/1900), maybe you have some suggestions? Trying to wrap my head around it.

Couldn't tag you on the other issue, that's why I created this over here.

Any suggestions would be highly appreciated! :)

Best,
David

**Comment by vlthemes** [comment]
Hi!

I`ll try to do this :)

**Comment by mapsteps** [comment]
Thanks @vlthemes,

appreciate it! :)

**Comment by mapsteps** [comment]
Fixed!

https://github.com/aristath/kirki/issues/1900
